### ISSUE TITLE
"Invalid URI: The hostname could not be parsed" error with pac pages upload/download

### ISSUE THREAD

**Issue by mannybellas** [microsoft/powerplatform-build-tools#1006]
**Describe the bug**
(note, this issue is also described here: https://github.com/microsoft/powerplatform-build-tools/discussions/971)

Whe trying to upload a Power Pages site (modelVersion 2), we get the following error (as shown in pac-log.txt)

```2024-08-22 07:57:16.0053 | ERR | bolt.module.paportal.PortalDataImporter :: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at bolt.module.paportal.PAPortalCommon.AddAttributeByType(Dictionary`2 values, String attributeName, Object attributeValue, XmlNode fieldNode, String entityName, String recordId, String filePath, ILocalizedStrings`1 locale)
   at bolt.module.paportal.core.PortalDirectoryParser.JsonEntityToDictionary(Dictionary`2 entityData, XmlNode entitySchemaNode, String entityFileName, String entityFolderPath)
   at bolt.module.paportal.core.PortalDirectoryParser.ParseEntitySingleFolder(String entityFolderPath, PortalExportImportMetaData metadata, XmlNode entitySchemaNode)
   at bolt.module.paportal.core.PortalDirectoryParser.ParseEntityFolder(PortalExportImportMetaData entityMetadata, XmlNode entityXMLNode)
   at bolt.module.paportal.PortalDataImporter.IterateSchema(String rootFolderPath, PortalDeploymentConfigProvider portalDeploymentConfigProvider, PortalDataManifestProvider portalManifestProvider, Guid websiteId, XmlNode xn)
   at bolt.module.paportal.PortalDataImporter.<>c__DisplayClass32_0.<IterateSchemaAndUploadData>b__1(XmlNode xn)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at bolt.module.paportal.PortalDataImporter.IterateSchemaAndUploadData(AuthProfile authProfile, String rootFolderPath)
   at bolt.module.paportal.PortalDataImporter.UploadData(AuthProfile authProfile)
```

**To Reproduce**
run pac command `run pac pages upload -env https://ENVIRONMENT.crm6.dynamics.com -p ./Pages/name-of-portal -mv 2 -f`

**Expected behavior**
`pac pages upload` should not fail.  Note: exporting and importing the Power Pages site a Solution works fine.

**Additional context:**
pac cli: Version: 1.33.5+g1621296

**Comment by mannybellas** [comment]
https://github.com/microsoft/powerplatform-build-tools/discussions/971 has some recent updates/comments with possible workarounds
