### ISSUE TITLE
Portal Upload fails due to pre-update plug-in

### ISSUE THREAD

**Issue by craig-lund** [microsoft/powerplatform-build-tools#172]
Recently, when uploading a portal to an environment with a community portal installed, the upload failed due to a pre-update plugin. This cause the site setting to NOT be associated with the website.

The plugin is:
Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate: Update of adx_sitesetting

With the error:

> Exception Message: Object reference not set to an instance of an object.
> 
> ErrorCode: -2147220891
> HexErrorCode: 0x80040265
> 
> ErrorDetails: 
> 	ApiExceptionSourceKey: Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService
> 	ApiStepKey: 41952d10-4e53-ea11-a814-000d3a3b1e97
> 	ApiDepthKey: 1
> 	ApiActivityIdKey: 2147f1bc-dc07-48b4-86bf-279b2e74e528
> 	ApiPluginSolutionNameKey: System
> 	ApiStepSolutionNameKey: System
> 	ApiExceptionCategory: ClientError
> 	ApiExceptionMessageName: IsvAborted
> 	ApiExceptionHttpStatusCode: 400
> 	OperationStatus: 0
> 	SubErrorCode: -2146233088
> 	Plugin: 
> 		PluginTrace: [Microsoft.Dynamics.Community.Plugins: Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate]
> [68a2d42a-8bf1-eb11-bad6-000d3af6d0a1: Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate: Update of adx_sitesetting]
> CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Entered Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.Execute()
> CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.ExecuteCrmPlugin(LocalPluginContext context)
>    at Microsoft.Dynamics.Community.Plugins.PluginBase.Execute(IServiceProvider serviceProvider)
> CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Exiting Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.Execute()
> 
> TraceText: 
> 	[Microsoft.Dynamics.Community.Plugins: Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate]
> 	[68a2d42a-8bf1-eb11-bad6-000d3af6d0a1: Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate: Update of adx_sitesetting]
> 	CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Entered Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.Execute()
> 	CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
> 	   at Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.ExecuteCrmPlugin(LocalPluginContext context)
> 	   at Microsoft.Dynamics.Community.Plugins.PluginBase.Execute(IServiceProvider serviceProvider)
> 	CorrelationId:78e3514a-7ede-4327-bcff-376667b2b006  Exiting Microsoft.Dynamics.Community.Plugins.SiteSetting_PreUpdate.Execute()

Turned off the plugin and the upload worked great.

Would be great to know if turning off plugins is available now or will be in the future.

**Comment by davidjenni** [comment]
@ameyaapte1 please comment

**Comment by ameyaapte1** [comment]
This sounds like a feature ask, will have to work with the Community portal team to work this out as currently the platform does not support disabling first party plugins although this can be done with using plugin parameters which can control the plugin logic. @ashishchoudhary001 @neerajnandwana-msft

**Comment by ameyaapte1** [comment]
@neerajnandwana-msft  Can you comment on this?

**Comment by petrochuk** [comment]
Closing because this is not build tools issue
