### ISSUE TITLE
Error: One or more errors occurred. -  Product Version: 1.29.6+g9020cf1; File Version: 1.29.6

### ISSUE THREAD

**Issue by philvbprogrammer** [microsoft/powerplatform-build-tools#627]
This website is not a portal that has blogs installed

2023-11-15 02:53:17.2139 | INF | bolt.module.paportal.PortalDataExporter :: Skipping download for entity adx_blog, Entity not exists in CDS
then repeated:
id 00000000-0000-0000-0000-000000000000 (64388432).
Source: mscorlib
Method: HandleReturnMessage
DateUTC: 15/11/2023
TimeUTC: 2:53:17 am
Error: Message: Could not find an entity with name adx_blog and id 00000000-0000-0000-0000-000000000000 (64388432).
ErrorCode: -2147220969
Trace: 
Error Details	:
ApiExceptionSourceKey	: Plugin/Microsoft.Crm.Sdk.Metadata.MetadataServiceProvider
ApiSourceActivityKey	: 
ApiExceptionOwnerKey	: OwnershipNotFoundInExceptionOwnerSettings
ApiOriginalExceptionKey	: Microsoft.Crm.BusinessEntities.CrmObjectNotFoundException: Could not find an entity with name adx_blog and id 00000000-0000-0000-0000-000000000000 (64388432). ---> Microsoft.Crm.BusinessEntities.CrmObjectNotFoundException: Could not find an entity with name adx_blog and id 00000000-0000-0000-0000-000000000000 (64388432).
   at Microsoft.Crm.Sdk.Metadata.MetadataReaderOptimized.RetrieveEntity(EntityFilters entityItems, String logicalName, Guid metadataId, Boolean retrieveAsIfPublished, ExecutionContext context)
   at Microsoft.Crm.Sdk.Metadata.MetadataServiceProvider.RetrieveEntity(EntityFilters entityItems, String logicalName, Guid metadataId, Boolean retrieveAsIfPublished, ExecutionContext context)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.<>c__DisplayClass6_0.<RunStep>b__0()
ApiStepKey	: 38b005c5-b7f8-4c22-97ed-a7abc9c22b6c
ApiDepthKey	: 1
ApiActivityIdKey	: f4fd854f-4f34-4af7-9783-22b37f8294de
ApiPluginSolutionNameKey	: System
ApiStepSolutionNameKey	: System
ApiExceptionCategory	: ClientError
ApiExceptionMessageName	: ObjectDoesNotExist
ApiExceptionHttpStatusCode	: 404

**Comment by MrRishabhJain** [comment]
Hey @philvbprogrammer, the error around adx_blog is by design, there must be some other error causing the issue. Are you still facing the issue?
