### ISSUE TITLE
pac paportal download - Error: One or more errors occurred.

### ISSUE THREAD

**Issue by janp17** [microsoft/powerplatform-build-tools#629]
This was not happening before.. but below is the error log.

```
Inner Exception Level 1	: 
==DataverseOperationException Info=======================================================================================
Source: Microsoft.PowerPlatform.Dataverse.Client
Error: External Authentication Requested but not configured correctly. 005
ErrorCode: -2146233088
DateUTC: Thu, 16, 11, 2023
TimeUTC: 3:45:43 am
HelpLink Url: Not Provided
======================================================================================================================
Inner Exception Level 2	: 
Source: Microsoft.Identity.Client.Extensions.Msal
Method: VerifyPersistence
DateUTC: Thu, 16, 11, 2023
TimeUTC: 3:45:43 am
Error: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
HelpLink Url: Not Provided
```

**Comment by nick626262** [comment]
Same issue here. Power platform tools just updated to v2.0.21 I suspect it's a change in pac v1.29.6. 

This has now stopped me from being able to work on portal changes as we integrate with github using vs code for our portal code.

**Comment by nick626262** [comment]
Upload to portal also isn't working either. 

pac powerpages upload --path D:\XXXX\git2\YYYYY\portal\ -dp dev1 --forceuploadall

Looks like it uploads a few items and then gives up

2023-11-16 10:39:01.4773 | FTL | bolt.Session :: One or more errors occurred.|EXCEPTION: Microsoft.PowerPlatform.Dataverse.Client.Utils.DataverseOperationException: External Authentication Requested but not configured correctly. 005 ---> Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
   at Microsoft.Identity.Client.Extensions.Msal.Storage.VerifyPersistence()
   at bolt.authentication.store.MsalExtensionCache.<CreateCacheHelperAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthApplication..ctor(IAuthKindDescription authKind, Uri authorityUri, MsalLoggingOptions msalLoggingOptions, IEnvirons environs, IProcessLauncher processLauncher, ILoggerFactory loggerFactory, IFeatureFlags featureFlags, Boolean useBrokerIfAvailable)
   at bolt.authentication.store.AuthTokenStore.<AcquireTokenSilentAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthTokenStore.<FetchTokenFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.dataverse.client.AuthWrapper.<GetAuthTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()
Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
   at Microsoft.Identity.Client.Extensions.Msal.Storage.VerifyPersistence()
   at bolt.authentication.store.MsalExtensionCache.<CreateCacheHelperAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthApplication..ctor(IAuthKindDescription authKind, Uri authorityUri, MsalLoggingOptions msalLoggingOptions, IEnvirons environs, IProcessLauncher processLauncher, ILoggerFactory loggerFactory, IFeatureFlags featureFlags, Boolean useBrokerIfAvailable)
   at bolt.authentication.store.AuthTokenStore.<AcquireTokenSilentAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthTokenStore.<FetchTokenFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.dataverse.client.AuthWrapper.<GetAuthTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()
2023-11-16 10:39:01.4773 | ERR | bolt.Session ::    at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Execute(OrganizationRequest request)
   at bolt.dataverse.client.CdsServiceClient.TrackCdsClientCall[TResult](Func`2 func, String memberName)
   at bolt.dataverse.client.ClientPrimitives.ExecuteMultiple(OrganizationRequestCollection requests)
   at bolt.module.paportal.PortalDataImporter.<>c__DisplayClass30_0.<ExecuteRequestsAndHandleResponse>b__0(OrganizationRequestCollection requests)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at bolt.module.paportal.PortalDataImporter.ExecuteRequestsAndHandleResponse(IEnumerable`1 requestList, CliExecutionContext cliInfra, Boolean isPreUpsert, Boolean suppressErrors)
   at bolt.module.paportal.PortalDataImporter.IterateSchemaAndUploadData(AuthProfile authProfile, String rootFolderPath)
   at bolt.module.paportal.PortalDataImporter.UploadData(AuthProfile authProfile)
   at bolt.module.paportal.verbs.PAPortalUploadVerb.Execute(Command command)
   at bolt.cli.CommandLine.VerbExecutor.ExecuteImpl(VerbBase verbInstance, Command command)
   at bolt.cli.CommandLine.VerbExecutor.<>c__DisplayClass4_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<ExecuteWithTelemetryAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<>c__DisplayClass11_0.<<RunVerbExecutorAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<RunVerbExecutorAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<ExecuteWithOutputAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at bolt.cli.CommandProcessor.<ProcessCommands>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandProcessor.<LaunchCommand>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.ModeManager.<Dispatch>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.Session.<Run>d__15.MoveNext()
2023-11-16 10:39:01.4773 | INF | bolt.Session :: End session. (sessionId: 28e52f94-2546-4d35-a30d-82a57ec9592e; ResponseCode: 500)

2023-11-16 10:39:01.5861 | INF | Microsoft.PowerPlatform.Tooling.BatchedTelemetry :: BatchedTransmitter`1.StartUploadProcess Started uploader with process id: 20060

**Comment by nick626262** [comment]
Rolled back to the previous version and that still works.

**Comment by janp17** [comment]
> Rolled back to the previous version and that still works.

Cool I will try this one, I also found other errors below.
Error: Message: Could not find an entity with name adx_communityforum and id 00000000-0000-0000-0000-000000000000 (228128192).
other entities as well..

**Comment by Cliveo** [comment]
Also facing this issue, cannot deploy or download portals, Also can't download data using pac

**Comment by frikishaan** [comment]
Same for me

> Rolled back to the previous version and that still works.

Rolling back to the previous version (v2.0.13) works for me too.

**Comment by vedg** [comment]
Please use the previous version of Power Apps CLI version 1.28.3.

We have added it to the list of known issues below.

https://learn.microsoft.com/en-us/power-pages/known-issues?tabs=Edge#microsoft-power-platform-cli-for-power-pages

**Comment by AndrewElans** [comment]
I see Power Platform Tools is released in v.2.0.23. Anyone tried that? Is the issue still there?
