### ISSUE TITLE
BUG: pac solution sync fails when SolutionRootPath is updated in the cdsproj

### ISSUE THREAD

**Issue by devkeydet** [microsoft/powerplatform-build-tools#662]
The default value for SolutionRootPath in a cdsproj file is _src_:
`<SolutionRootPath>src</SolutionRootPath>`

If I change the name of the `src`  folder to `solution`  and update the SolutionRootPath in the cdsproj to `<SolutionRootPath>solution</SolutionRootPath>`, then I get the following error:
![image](https://github.com/microsoft/powerplatform-build-tools/assets/4499296/40beea41-e822-4b50-93ff-04c976fad789)

I would like to rename the folder so I can have a folder structure that looks like this.
![image](https://github.com/microsoft/powerplatform-build-tools/assets/4499296/5d35d7e6-00bb-40ae-bbda-01b5cac7871f)

**Comment by BetimBeja** [comment]
Hi @devkeydet,
just had this same issue with v 1.31.6. 

```
2024-05-15 09:22:27.4434 | INF | bolt.Session :: Product Version: 1.31.6+g9147a23; File Version: 1.31.6
2024-05-15 09:22:27.4793 | INF | bolt.Session :: Start new session. (sessionId: 35907ba0-dd78-48e5-8e4b-fa4c709cbedf; operationId: d3ea9b3b3b7010ed09eb2d428a445771; userId: af333a78-c362-41c0-a1f4-4f260bf120f3; nonInteractiveMode: False)
2024-05-15 09:22:27.6290 | INF | bolt.cli.CommandProcessor :: StartExecutingVerb (Verbs: ["solution","sync"])
2024-05-15 09:22:27.6623 | INF | bolt.cli.Verb :: Executing verb 'solution sync' with arguments --solution-folder,--async.
2024-05-15 09:22:27.6803 | INF | bolt.cli.CommandLine.VerbExecutor :: PerformAuthenticationAsync - Getting auth profile with following options: { AuthKind = DATAVERSE, IsRequired = True, ShowProfileMessages = True, VerbDisableAutoOSLogin = False, SkipValidation = False }
2024-05-15 09:22:28.0170 | INF | bolt.cli.CommandLine.VerbExecutor :: PerformAuthenticationAsync - Using auth profile: { Kind = UNIVERSAL, ProfileType = Application, AadObjectId = 1df8a95f-10c0-40e9-8ed3-bb079ae0e181, CloudInstance = Public, TenantId = 06a94acd-****-****-****-1478****fda3, User = 352a155f-4923-46d2-9d73-84b7b4de099b }
2024-05-15 09:22:28.0658 | INF | bolt.cli.CommandProcessor :: EndExecutingVerb (Success: False, Execution Time(ms): 426)
2024-05-15 09:22:28.0967 | FTL | bolt.Session :: SolutionFileNotFound|EXCEPTION: bolt.version.SolutionXmlVersioningException: SolutionFileNotFound
   at bolt.version.SolutionVersionUpdateProvider.GetSolutionUniqueName(String solutionXmlFilePath)
   at bolt.module.solution.verbs.SolutionSyncVerb.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<ExecuteImplAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<>c__DisplayClass8_1.<<ExecuteAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<ExecuteWithTelemetryAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<>c__DisplayClass11_0.<<RunVerbExecutorAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<RunVerbExecutorAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<ExecuteWithOutputAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at bolt.cli.CommandProcessor.<ProcessCommands>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandProcessor.<LaunchCommand>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.ModeManager.<Dispatch>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.Session.<Run>d__14.MoveNext()
2024-05-15 09:22:28.0967 | ERR | bolt.Session ::    at bolt.version.SolutionVersionUpdateProvider.GetSolutionUniqueName(String solutionXmlFilePath)
   at bolt.module.solution.verbs.SolutionSyncVerb.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<ExecuteImplAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<>c__DisplayClass8_1.<<ExecuteAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<ExecuteWithTelemetryAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandLine.VerbExecutor.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<>c__DisplayClass11_0.<<RunVerbExecutorAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<RunVerbExecutorAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<ExecuteWithOutputAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at bolt.cli.CommandProcessor.<ProcessCommands>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.CommandProcessor.<LaunchCommand>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.ModeManager.<Dispatch>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.Session.<Run>d__14.MoveNext()
2024-05-15 09:22:28.0967 | INF | bolt.Session :: End session. (sessionId: 35907ba0-dd78-48e5-8e4b-fa4c709cbedf; ResponseCode: 500)

2024-05-15 09:22:28.2475 | INF | Microsoft.PowerPlatform.Tooling.BatchedTelemetry :: BatchedTransmitter`1.StartUploadProcess Started uploader with process id: 5432
```

**Comment by devkeydet** [comment]
When I filed this, I wasn't on the team.  I am now.  I'll take a look at the code.  I suspect it's a relatively simple fix.  We just have a lot of work on our plate preparing for the build conference and not gotten around to this one.

**Comment by BetimBeja** [comment]
there are a lot of `pac` related issues in this repository and in https://github.com/microsoft/powerplatform-vscode 

I think we need a better guidance on where to open the issues for `pac` 😄 and also someone should transfer the issues between repositories where possible (in the fullness of time)
