### ISSUE TITLE
Enhancement Request: Improved error messaging for pac paportal upload

### ISSUE THREAD

**Issue by Joseph-Duty-VA** [microsoft/powerplatform-build-tools#712]
I am receiving an error about a file not being able to be uploaded.  The error description is clear in what went wrong, but its not possible to tell which record errored out.  It would be helpful if either a record id or file name or some other identifier was provided to know which file could not be uploaded.  With hundreds of files, and several dozen blocked file extensions, it is challenging to figure out which files are problematic.  

here's a snippet of the console output...
  
Updated record(s) for table: adx_websitelanguage

Updated record(s) for table: adx_ad

_XRM Network error: The attachment is either not a valid type or is too large. It cannot be uploaded or downloaded.

XRM Network error: The attachment is either not a valid type or is too large. It cannot be uploaded or downloaded.

XRM Network error: The attachment is either not a valid type or is too large. It cannot be uploaded or downloaded.

XRM Network error: The attachment is either not a valid type or is too large. It cannot be uploaded or downloaded._

Updated record(s) for table: annotation

**Comment by MrRishabhJain** [comment]
Hey @Joseph-Duty-VA we have made enhancements in this area, can you please update to 1.32.x version of PAC cli and try again?

**Comment by Glideh** [comment]
_Ubuntu 24.04, dotnet 8.0.108, pac cli 1.32.8+gf89d946_

I'm having that too:

```
pac powerpages upload -p ./site -f -mv 2 -dp rec -env https://env

//[...]
Exception Type: System.AggregateException
```

Checking the log I'm seeing the

> The attachment is either not a valid type or is too large. It cannot be uploaded or downloaded.

Stack:

```
bolt.Session ::    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 
bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 
bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverythin
g, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at bolt.module.paportal.PortalDataImporter.UploadWebFileContent(IEnumerable`1 webfiles, CliExecutionContext cliInfra) in C:\__w\1\s\src\cli\bolt.module.paportal\core\PortalDataImporter.cs:line 596
   at bolt.module.paportal.PortalDataImporter.IterateSchemaAndUploadData(AuthProfile authProfile, String rootFolderPath) in C:\__w\1\s\src\cli\bolt.module.paportal\core\PortalDataImporter.cs:line 489
   at bolt.module.paportal.PortalDataImporter.UploadData(AuthProfile authProfile) in C:\__w\1\s\src\cli\bolt.module.paportal\core\PortalDataImporter.cs:line 104
   at bolt.module.paportal.verbs.PAPortalUploadVerb.ExecuteAsync(Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.module.paportal\verbs\PAPortalUploadVerb.cs:line 107
   at bolt.cli.CommandLine.VerbExecutor.ExecuteImplAsync(VerbBase verbInstance, Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 193
   at bolt.cli.CommandLine.VerbExecutor.<>c__DisplayClass8_1.<<ExecuteAsync>b__2>d.MoveNext() in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 63
--- End of stack trace from previous location ---
   at bolt.cli.CommandLine.VerbExecutor.ExecuteWithTelemetryAsync(VerbExecutionContext execContext, Func`1 executeCoreFn) i
n C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 228
   at bolt.cli.CommandLine.VerbExecutor.ExecuteAsync(VerbExecutionContext execContext, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 59
   at bolt.cli.Verb.<>c__DisplayClass11_0.<<RunVerbExecutorAsync>b__0>d.MoveNext() in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 237
--- End of stack trace from previous location ---
   at bolt.cli.Verb.RunVerbExecutorAsync(IProcessCommandContext context, Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 229
   at bolt.cli.Verb.ExecuteWithOutputAsync(IProcessCommandContext context, Command command, Queue`1 nextCommands, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 174
   at bolt.cli.Verb.ExecuteAsync(IProcessCommandContext context, Command command, Queue`1 nextCommands, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 80
   at bolt.cli.CommandProcessor.ProcessCommands(Queue`1 commands, IVerbFactory factory) in C:\__w\1\s\src\cli\bolt.cli\CommandProcessor.cs:line 183
   at bolt.cli.CommandProcessor.LaunchCommand(IReadOnlyList`1 args, UserHelpText userHelpText, Boolean isNonInteractiveModeEnabled) in C:\__w\1\s\src\cli\bolt.cli\CommandProcessor.cs:line 94
   at bolt.cli.ModeManager.Dispatch(ProgramArguments args) in C:\__w\1\s\src\cli\bolt.cli\ModeManager.cs:line 44
   at bolt.Session.Run(ProgramArguments args) in C:\__w\1\s\src\cli\bolt\Session.cs:line 337
2024-09-04 12:20:15.2736 | INF | bolt.Session :: End session. (sessionId: 470e28c2-523f-4652-a65d-c838702885a0; ResponseCode: 500)
```

**Comment by Glideh** [comment]
I don't have the issue anymore since I worked that around, but I'll check next time. Thanks for the update.
