### ISSUE TITLE
SPN auth broken on MacOS - System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.AccessToken

### ISSUE THREAD

**Issue by jjdd12** [microsoft/powerplatform-build-tools#716]
Unable to create a Service Principal using `pac auth create`  on a Mac M1 

In the following manner 

`pac auth create --name MyOrg-SPN --applicationId 00000000-0000-0000-0000-000000000000 --clientSecret $clientSecret --tenant 00000000-0000-0000-0000-000000000000
`

See the logs below

```
2024-01-18 03:41:13.0419 | INF | bolt.Session :: Product Version: 1.29.11+g9e2b163; File Version: 1.29.11
2024-01-18 03:41:13.0505 | INF | bolt.Session :: Start new session. (sessionId:; nonInteractiveMode: False)
2024-01-18 03:41:13.1024 | INF | bolt.cli.CommandProcessor :: StartExecutingVerb (Verbs: ["auth","create"])
2024-01-18 03:41:13.1091 | INF | bolt.cli.Verb :: Executing verb 'auth create' with arguments --name,--applicationId,--clientSecret,--tenant,--environment.
2024-01-18 03:41:13.1195 | INF | bolt.cli.TelemetryImplementation.PacTelemetryClient :: SetCurrentUser called with user=; dataverse=; profile=.
2024-01-18 03:41:13.1479 | INF | bolt.module.auth.AuthModule :: Creating UNIVERSAL auth profile
2024-01-18 03:41:13.1509 | INF | bolt.authentication.store.AuthTokenStore :: CreateAuthProfile: Authority for  is https://login.microsoftonline.com/
2024-01-18 03:41:13.1509 | INF | bolt.authentication.store.AuthTokenStore :: CreateAuthProfile: Acquiring token for 
2024-01-18 03:41:13.2405 | INF | bolt.authentication.store.ServicePrincipalCache :: Initializing service principal cache
2024-01-18 03:41:13.2706 | INF | bolt.cli.TelemetryImplementation.RegionalOneDSTelemetryConfigurationProvider :: Flushing the default config for environment Microsoft.PowerPlatform.Tooling.OneDS.OneDSTelemetryConfiguration.
2024-01-18 03:41:13.2711 | INF | bolt.cli.TelemetryImplementation.RegionalOneDSTelemetryConfigurationProvider :: Flushing the config geo US.
2024-01-18 03:41:14.2832 | INF | bolt.cli.TelemetryImplementation.RegionalOneDSTelemetryConfigurationProvider :: Flushing the config geo EU.
2024-01-18 03:41:14.2841 | INF | bolt.cli.TelemetryImplementation.RegionalOneDSTelemetryConfigurationProvider :: Instance disposed.
2024-01-18 03:41:14.2864 | INF | bolt.cli.CommandProcessor :: EndExecutingVerb (Success: False, Execution Time(ms): 182)
2024-01-18 03:41:14.2966 | FTL | bolt.Session :: The JSON value could not be converted to System.String. Path: $.AccessToken | LineNumber: 0 | BytePositionInLine: 16.|EXCEPTION: System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.AccessToken | LineNumber: 0 | BytePositionInLine: 16.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at bolt.authentication.store.ServicePrincipalCache.CacheSecret(String clientId, String clientSecret, Boolean acceptCleartextCache) in C:\__w\1\s\src\cli\bolt.authentication\store\ServicePrincipalCache.cs:line 111
   at bolt.authentication.store.AuthTokenStore.AcquireTokenAsync(IAuthKindDescription authKind, AuthorityInfo authorityInfo, AuthResource resource, NetworkCredential optionalCredential, AuthenticationFlow authenticationFlow, String certificateDiskPath, Boolean acceptCleartextCaching) in C:\__w\1\s\src\cli\bolt.authentication\store\AuthTokenStore.cs:line 212
   at bolt.authentication.store.AuthTokenStore.CreateAuthProfile(AuthName authName, AuthKind kind, AuthResource resource, CloudInstance cloudInstanceHint, NetworkCredential optionalCredential, AuthenticationFlow authenticationFlow, Guid tenantId, String certificateDiskPath, Boolean acceptCleartextCaching) in C:\__w\1\s\src\cli\bolt.authentication\store\AuthTokenStore.cs:line 76
   at bolt.module.auth.verbs.AuthCreateVerb.ExecuteInternalAsync(Command command, NetworkCredential optionalCredential, AuthenticationFlow authenticationFlow, Guid tenantId, String certificateDiskPath, Boolean acceptCleartextCaching) in C:\__w\1\s\src\cli\bolt.module.auth\verbs\AuthCreateVerb.cs:line 373
   at bolt.module.auth.verbs.AuthCreateVerb.ExecuteAsync(Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.module.auth\verbs\AuthCreateVerb.cs:line 309
   at bolt.cli.CommandLine.VerbExecutor.ExecuteImplAsync(VerbBase verbInstance, Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 93
   at bolt.cli.CommandLine.VerbExecutor.<>c__DisplayClass4_0.<<ExecuteAsync>b__0>d.MoveNext() in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 47
--- End of stack trace from previous location ---
   at bolt.cli.CommandLine.VerbExecutor.ExecuteWithTelemetryAsync(VerbExecutionContext execContext, Func`1 executeCoreFn) in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 143
   at bolt.cli.CommandLine.VerbExecutor.ExecuteAsync(VerbExecutionContext execContext, Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 43
   at bolt.cli.Verb.<>c__DisplayClass11_0.<<RunVerbExecutorAsync>b__0>d.MoveNext() in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 232
--- End of stack trace from previous location ---
   at bolt.cli.Verb.RunVerbExecutorAsync(IProcessCommandContext context, Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 223
   at bolt.cli.Verb.ExecuteWithOutputAsync(IProcessCommandContext context, Command command, Queue`1 nextCommands, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 175
   at bolt.cli.Verb.ExecuteAsync(IProcessCommandContext context, Command command, Queue`1 nextCommands, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 80
   at bolt.cli.CommandProcessor.ProcessCommands(Queue`1 commands, IVerbFactory factory) in C:\__w\1\s\src\cli\bolt.cli\CommandProcessor.cs:line 183
   at bolt.cli.CommandProcessor.LaunchCommand(IReadOnlyList`1 args, UserHelpText userHelpText, Boolean isNonInteractiveModeEnabled) in C:\__w\1\s\src\cli\bolt.cli\CommandProcessor.cs:line 94
   at bolt.cli.ModeManager.Dispatch(ProgramArguments args) in C:\__w\1\s\src\cli\bolt.cli\ModeManager.cs:line 25
   at bolt.Session.Run(ProgramArguments args) in C:\__w\1\s\src\cli\bolt\Session.cs:line 329
System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
2024-01-18 03:41:14.2989 | ERR | bolt.Session ::    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at bolt.authentication.store.ServicePrincipalCache.CacheSecret(String clientId, String clientSecret, Boolean acceptCleartextCache) in C:\__w\1\s\src\cli\bolt.authentication\store\ServicePrincipalCache.cs:line 111
   at bolt.authentication.store.AuthTokenStore.AcquireTokenAsync(IAuthKindDescription authKind, AuthorityInfo authorityInfo, AuthResource resource, NetworkCredential optionalCredential, AuthenticationFlow authenticationFlow, String certificateDiskPath, Boolean acceptCleartextCaching) in C:\__w\1\s\src\cli\bolt.authentication\store\AuthTokenStore.cs:line 212
   at bolt.authentication.store.AuthTokenStore.CreateAuthProfile(AuthName authName, AuthKind kind, AuthResource resource, CloudInstance cloudInstanceHint, NetworkCredential optionalCredential, AuthenticationFlow authenticationFlow, Guid tenantId, String certificateDiskPath, Boolean acceptCleartextCaching) in C:\__w\1\s\src\cli\bolt.authentication\store\AuthTokenStore.cs:line 76
   at bolt.module.auth.verbs.AuthCreateVerb.ExecuteInternalAsync(Command command, NetworkCredential optionalCredential, AuthenticationFlow authenticationFlow, Guid tenantId, String certificateDiskPath, Boolean acceptCleartextCaching) in C:\__w\1\s\src\cli\bolt.module.auth\verbs\AuthCreateVerb.cs:line 373
   at bolt.module.auth.verbs.AuthCreateVerb.ExecuteAsync(Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.module.auth\verbs\AuthCreateVerb.cs:line 309
   at bolt.cli.CommandLine.VerbExecutor.ExecuteImplAsync(VerbBase verbInstance, Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 93
   at bolt.cli.CommandLine.VerbExecutor.<>c__DisplayClass4_0.<<ExecuteAsync>b__0>d.MoveNext() in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 47
--- End of stack trace from previous location ---
   at bolt.cli.CommandLine.VerbExecutor.ExecuteWithTelemetryAsync(VerbExecutionContext execContext, Func`1 executeCoreFn) in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 143
   at bolt.cli.CommandLine.VerbExecutor.ExecuteAsync(VerbExecutionContext execContext, Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\CommandLine\VerbExecutor.cs:line 43
   at bolt.cli.Verb.<>c__DisplayClass11_0.<<RunVerbExecutorAsync>b__0>d.MoveNext() in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 232
--- End of stack trace from previous location ---
   at bolt.cli.Verb.RunVerbExecutorAsync(IProcessCommandContext context, Command command, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 223
   at bolt.cli.Verb.ExecuteWithOutputAsync(IProcessCommandContext context, Command command, Queue`1 nextCommands, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 175
   at bolt.cli.Verb.ExecuteAsync(IProcessCommandContext context, Command command, Queue`1 nextCommands, CancellationToken cancellationToken) in C:\__w\1\s\src\cli\bolt.cli\Verb.cs:line 80
   at bolt.cli.CommandProcessor.ProcessCommands(Queue`1 commands, IVerbFactory factory) in C:\__w\1\s\src\cli\bolt.cli\CommandProcessor.cs:line 183
   at bolt.cli.CommandProcessor.LaunchCommand(IReadOnlyList`1 args, UserHelpText userHelpText, Boolean isNonInteractiveModeEnabled) in C:\__w\1\s\src\cli\bolt.cli\CommandProcessor.cs:line 94
   at bolt.cli.ModeManager.Dispatch(ProgramArguments args) in C:\__w\1\s\src\cli\bolt.cli\ModeManager.cs:line 25
   at bolt.Session.Run(ProgramArguments args) in C:\__w\1\s\src\cli\bolt\Session.cs:line 329
2024-01-18 03:41:14.2989 | INF | bolt.Session :: End session. (sessionId:ResponseCode: 500)
```

**Comment by nilokillian** [comment]
Mac mini 2018 the same issue

**Comment by tehcrashxor** [comment]
Issue found and fixed in the PAC repo.
Fix should roll out with the next release in 2-ish weeks

**Comment by snizar007** [comment]
Hello @jjdd12, @nilokillian - New PAC CLI release has been published which you can update via "dotnet tool update". 
Please let us know if we can close this issue.

**Comment by snizar007** [comment]
Fix released.
